### ISSUE TITLE
Crashes when launching MassEffect2.exe

### ISSUE THREAD

**Issue by ghost** [Erik-JS/masseffect-binkw32#8]
I'm having the same issue as #7. When I copy the 2 DLL files over, it no longer launches.
I'm running it through Steam, not Origin, so I just get a standard "Mass Effect 2 has stopped working" error.

I was able to install the C++ 2012 update 4 which you linked. Both the x64 and the x86 ones. I'm not able to install the vcredist_arm.exe file though. When I try, it gives me an error that its not a valid Win32 application.

Let me know if there's other information I should provide. I'm new to both modding and this community.

**Comment by Erik-JS** [comment]
Your MassEffect2.exe's version is 01604.00 / 1.2.1604.0, right?

Regarding VC++ 2012, only the x86 (32-bit) version is needed for the binkw32 patch. The x64 version won't cause any troubles if you decide to install that too. Don't bother with vcredist_arm.exe, as far as I remember I never installed that here.

**Comment by ghost** [comment]
Yep. It's that version.
And yeah, I've installed both the x64 and x86 versions. I also tried uninstalling and then reinstalling them.

**Comment by Erik-JS** [comment]
There's something I just noticed here. I reinstalled ME2 and downloaded the 7z file as any other user would do. Once extracted, both DLL files are marked as "blocked", even though I'm still using the same computer and OS they actually came from.

Game still works here with "blocked" DLL's, maybe you should try unblocking them there and see if this will solve this issue.

http://www.thewindowsclub.com/fix-windows-blocked-access-file

**Comment by ghost** [comment]
I don't seem to have that option on the general tab for files. Below attributes there's just a blank space.
I'm using Win7 64-bit btw.

**Comment by Erik-JS** [comment]
Do you want to try a version recompiled in VS 2015? Here:

[binkw32-me2.zip](https://github.com/Erik-JS/masseffect-binkw32/files/691823/binkw32-me2.zip)

https://www.microsoft.com/en-us/download/details.aspx?id=48145

Btw, I intend to switch everything to VS 2015, including PSE and my other repositories.

EDIT:
[binkw32-me2-blank.zip](https://github.com/Erik-JS/masseffect-binkw32/files/692190/binkw32-me2-blank.zip)
This "blank" version (also from VS 2015) has no file logging, no memory patching and no ASI loader. It has only the absolute basic for DLL wrapping. This should be the same thing as using the original binkw32.dll.

**Comment by ghost** [comment]
Sorry for the delay in responding back to this. Hit a frustrating brick wall...

I can't get the VS 2015 Redistributable to install correctly (neither the x86 or x64). It reaches a point near the end of the installation "Processing: Windows7_MSU_x86" or "Processing: Windows7_MSU_x64" and all progress stops. Let it ran overnight once as well, to no luck. Stopping the installer and trying to "Repair" afterwards has been the same result. 

Afterwards, it will still list the 2015 Redistributable in the installed programs list, but when I try to run ME2 with the new DLL files, I get startup errors again, albeit different ones.
http://imgur.com/a/oRjjE

I've tried googling around for some fixes for the 2015 Redistributable not installing, but I haven't seen anything concrete. And honestly, I'm getting pretty worn out from this whole ordeal. I also contacted the original creator of the mod (ALOT for ME2), and he's been quite abrasive with advice on this issue. 

I greatly appreciate you helping me with this, but I think unless there's another solution you have in mind, I'm ready to just throw in the towel and go back to Vanilla ME2.

**Comment by Erik-JS** [comment]
I have an alternate solution, but that will take some time... if you can wait until Friday or Saturday.

**Comment by ghost** [comment]
sure

**Comment by Erik-JS** [comment]
[binkw32-me2_gcc_blank.zip](https://github.com/Erik-JS/masseffect-binkw32/files/705675/binkw32-me2_gcc_blank.zip)
[binkw32-me2_gcc_alt.zip](https://github.com/Erik-JS/masseffect-binkw32/files/705674/binkw32-me2_gcc_alt.zip)

These files were compiled under GCC. They don't require any redistributable to be installed. Practically, they work on anyone's machine without too much fuss, but I'm still keeping my decision of using VC++ 2015 for the next release.

Blank: basic DLL proxy. No special features.

Alt: DLL proxy with official features, but with alternate file logging.

**Comment by ghost** [comment]
The blank one worked!!
Thank You! Thank You! Thank You! Thank You! Thank You! Thank You!!!!!

**Comment by Erik-JS** [comment]
Wait... what?

The blank version is the same thing as using the original binkw32.dll! It only means that there's nothing in your PC blocking fake DLL's.

I assumed that the mod you have is in DLC format and you needed the custom binkw32 in order to authorize it. Are you able to play the mod with the blank binkw32?

**Comment by ghost** [comment]
Sorry! It was the alt version.
I was tired last night and I mixed up both of the folders when I extracted them, haha.

**Comment by Mgamerz** [comment]
@Erik-JS 
File blocking was only introduced in Windows 8 and above. Windows 7 does not attempt to block files. I've never found an instance where file blocking was actually useful however.

**Comment by Erik-JS** [comment]
The "file came from another computer" thing has been around since XP as far as I remember. Is this file blocking you're talking about, or is it something else?

For the record, I figured that the problem @LightningCrabz had was because of access denied for creating files (I got the same error message he got when I tried to write a log on an unavailable path). He could most likely fix his problem by running the game as admin, but I decided to look out for some less drastic method.

The alternate file logging I mentioned involves a custom printf function which checks if the log file has been successfully created before attempting to write messages to it. The next code update will attempt to create the log on the Documents folder, then the game's folder if the Documents folder cannot be retrieved, then no log at all if it fails to create the file in the chosen path.

_but I'm still keeping my decision of using VC++ 2015 for the next release_
...because GCC bitches about PathCombine. 😠 
The alt version linked above tries the game's path only, if it fails then there won't be any logs.
